### ISSUE TITLE
Canal de comunicação e Readme

### ISSUE THREAD

**Issue by raphaelts3** [devbythebook/meetings#1]
@joaofnds tu já tem um Slack ou Discord pro grupo? Se já tiver cola aqui pra gente, se não tiver ainda e quiser que crie, o que acha que seria melhor entre Discord/Slack?

Esse final de semana vou tentar montar um README pra gente com alguns e já deixar o canal lá também. 

Por fim, se quiser me adicionar no projeto, ficaria feliz de ajudar com as contribuições, assim como ajudar com possíveis PRs que devem[espero] chegar.

**Comment by joaofnds** [comment]
Eu ia botar um README com o slack ontem, mas acabei deixando pra hoje porque já estava tarde. Vou criar o arquivo e botar só o link do slack por enquanto, fica à vontade pra adicionar conteúdo depois!

Eu criei o slack há um tempo já. Acabei criando lá porque tive uma boa experiência em slacks de outros grupos, pessoal é bem ativo.

Vou te adicionar aqui sim, obrigado pela disposição em ajudar!

**Comment by joaofnds** [comment]
Creio que resolvemos as questões levantadas. Se estou deixando passar algo comenta aqui que discutimos!

Obrigado por ajudar! 👊
